<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Produk;

class ProdukSeeder extends Seeder
{
    public function run(): void
    {
        Produk::insert([
            [
                'nama' => 'Sepatu Kobe Porto',
                'kategori_id' => 1,
                'merek_id' => 1,
                'deskripsi' => 'Sepatu Kobe Porto merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt',
                'gambarproduk' => 'KOBE-PORTO-1.png',
                'gambarproduk1' => 'KOBE-PORTO-1.avif',
                'gambarproduk2' => 'KOBE-PORTO-2.jpg',
                'gambarproduk3' => 'KOBE-PORTO-3.jpg',
                'harga' => 1800000,
                'stok' => 10,
            ],
            [
                'nama' => 'Headband Nike',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Headband Nike merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt',
                'gambarproduk' => 'HEADBAND-1.png',
                'gambarproduk1' => 'HEADBAND-2.avif',
                'gambarproduk2' => 'HEADBAND-2.avif',
                'gambarproduk3' => 'HEADBAND-2.avif',
                'harga' => 100000,
                'stok' => 15,
            ],
            [
                'nama' => 'Jersey Lakers',
                'kategori_id' => 2,
                'merek_id' => 4,
                'deskripsi' => 'Jersey Lakers merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt',
                'gambarproduk' => 'LAKERS-1.png',
                'gambarproduk1' => 'lakers1.avif',
                'gambarproduk2' => 'lakers2.avif',
                'gambarproduk3' => 'lakers2.avif',
                'harga' => 3500000,
                'stok' => 10,
            ],
            [
                'nama' => 'Bola Basket ELITE',
                'kategori_id' => 3,
                'merek_id' => 3,
                'deskripsi' => 'Bola Basket Molten merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'BALL-ELITE-1.png',
                'gambarproduk1' => 'BALL-ELITE-2.avif',
                'gambarproduk2' => 'BALL-ELITE-2.avif',
                'gambarproduk3' => 'BALL-ELITE-2.avif',
                'harga' => 450000,
                'stok' => 20,
            ],
            [
                'nama' => 'Celana Lakers GWS',
                'kategori_id' => 4,
                'merek_id' => 4,
                'deskripsi' => 'Celana Lakers GWS merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'GWS-1.png',
                'gambarproduk1' => 'lakersp-1.avif',
                'gambarproduk2' => 'lakersp-2.avif',
                'gambarproduk3' => 'lakersp-2.avif',
                'harga' => 2000000,
                'stok' => 55,
            ],
            [
                'nama' => 'Sepatu GT Cut',
                'kategori_id' => 1,
                'merek_id' => 1,
                'deskripsi' => 'Sepatu GT Cut merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'GT-1.png',
                'gambarproduk1' => 'GT-4.jpg',
                'gambarproduk2' => 'GT-3.jpg',
                'gambarproduk3' => 'GT-2.jpg',
                'harga' => 1100000,
                'stok' => 15,
            ],
            [
                'nama' => 'Sepatu Giannis',
                'kategori_id' => 1,
                'merek_id' => 1,
                'deskripsi' => 'Sepatu Giannis merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'GIANNIS-1.png',
                'gambarproduk1' => 'GIANNIS-3.jpg',
                'gambarproduk2' => 'GIANNIS-6.avif',
                'gambarproduk3' => 'GIANNIS-7.avif',
                'harga' => 1000000,
                'stok' => 35,
            ],
            [
                'nama' => 'Baju New York',
                'kategori_id' => 2,
                'merek_id' => 1,
                'deskripsi' => 'Baju New York merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'NEWYORK-1.png',
                'gambarproduk1' => 'NEWYORK-1.avif',
                'gambarproduk2' => 'NEWYORK-2.avif',
                'gambarproduk3' => 'NEWYORK-2.avif',
                'harga' => 1500000,
                'stok' => 45,
            ],
            [
                'nama' => 'Jersey North Carolina',
                'kategori_id' => 2,
                'merek_id' => 1,
                'deskripsi' => 'Jersey North Carolina merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'NC-1.png',
                'gambarproduk1' => 'NC-1.avif',
                'gambarproduk2' => 'NC-2.jpg',
                'gambarproduk3' => 'NC-2.jpg',
                'harga' => 3000000,
                'stok' => 16,
            ],
            [
                'nama' => 'Hand Guard Nike',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Hand Guard Nike merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'GUARD-1.png',
                'gambarproduk1' => 'GUARD-2.jpg',
                'gambarproduk2' => 'GUARD-2.jpg',
                'gambarproduk3' => 'GUARD-2.jpg',
                'harga' => 80000,
                'stok' => 40,
            ],
            [
                'nama' => 'Celana Lakers',
                'kategori_id' => 4,
                'merek_id' => 1,
                'deskripsi' => 'Celana Lakers MNK merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'CELANA-LAKERS-1.png',
                'gambarproduk1' => 'CELANA-LAKERS-1.avif',
                'gambarproduk2' => 'CELANA-LAKERS-2.avif',
                'gambarproduk3' => 'CELANA-LAKERS-3.avif',
                'harga' => 2000000,
                'stok' => 15,
            ],
            [
                'nama' => 'Baju PHIL',
                'kategori_id' => 2,
                'merek_id' => 1,
                'deskripsi' => 'Baju PHIL merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'PHIL-1.png',
                'gambarproduk1' => 'PHIL-1.avif',
                'gambarproduk2' => 'PHIL-2.avif',
                'gambarproduk3' => 'PHIL-2.avif',
                'harga' => 1800000,
                'stok' => 20,
            ],
            [
                'nama' => 'Sepatu Anthony',
                'kategori_id' => 1,
                'merek_id' => 2,
                'deskripsi' => 'Sepatu Anthony merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'ANTHONY-1.png',
                'gambarproduk1' => 'ANTHONY-1.avif',
                'gambarproduk2' => 'ANTHONY-2.avif',
                'gambarproduk3' => 'ANTHONY-3.avif',
                'harga' => 2400000,
                'stok' => 5,
            ],
            [
                'nama' => 'Bola Basket Adidas',
                'kategori_id' => 3,
                'merek_id' => 2,
                'deskripsi' => 'Bola Basket Adidas merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'BALL-ADIDAS-1.png',
                'gambarproduk1' => 'BALL-ADIDAS-1.avif',
                'gambarproduk2' => 'BALL-ADIDAS-2.avif',
                'gambarproduk3' => 'BALL-ADIDAS-3.avif',
                'harga' => 400000,
                'stok' => 15,
            ],
            [
                'nama' => 'Bola Basket Jordan',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Bola Basket Jordan merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'BALL-JORDAN-1.png',
                'gambarproduk1' => 'BALL-JORDAN-1.avif',
                'gambarproduk2' => 'BALL-JORDAN-2.avif',
                'gambarproduk3' => 'BALL-JORDAN-2.avif',
                'harga' => 450000,
                'stok' => 12,
            ],
            [
                'nama' => 'Bola Basket Strip',
                'kategori_id' => 3,
                'merek_id' => 2,
                'deskripsi' => 'Bola Basket Strip merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'BALL-STRIP-1.png',
                'gambarproduk1' => 'BALL-STRIP-1.avif',
                'gambarproduk2' => 'BALL-STRIP-2.avif',
                'gambarproduk3' => 'BALL-STRIP-3.avif',
                'harga' => 400000,
                'stok' => 16,
            ],
            [
                'nama' => 'Bottle Chug',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Bottle Chug merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'BOTTLE-CHUG-1.png',
                'gambarproduk1' => 'BOTTLE-CHUG-1.avif',
                'gambarproduk2' => 'BOTTLE-CHUG-2.avif',
                'gambarproduk3' => 'BOTTLE-CHUG-2.avif',
                'harga' => 200000,
                'stok' => 16,
            ],
            [
                'nama' => 'Bottle Recharge',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Bottle Recharge merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'BOTTLE-RECHARGE-1.png',
                'gambarproduk1' => 'BOTTLE-RECHARGE-1.avif',
                'gambarproduk2' => 'BOTTLE-RECHARGE-1.avif',
                'gambarproduk3' => 'BOTTLE-RECHARGE-1.avif',
                'harga' => 200000,
                'stok' => 16,
            ],
            [
                'nama' => 'Sepatu Damex',
                'kategori_id' => 1,
                'merek_id' => 2,
                'deskripsi' => 'Sepatu Damex merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'DAMEX-1.png',
                'gambarproduk1' => 'DAMEX-1.avif',
                'gambarproduk2' => 'DAMEX-2.avif',
                'gambarproduk3' => 'DAMEX-3.avif',
                'harga' => 1500000,
                'stok' => 4,
            ],
            [
                'nama' => 'Sepatu DON',
                'kategori_id' => 1,
                'merek_id' => 2,
                'deskripsi' => 'Sepatu DON merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'DON-ADIDAS-1.png',
                'gambarproduk1' => 'DON-ADIDAS-1.avif',
                'gambarproduk2' => 'DON-ADIDAS-2.avif',
                'gambarproduk3' => 'DON-ADIDAS-3.avif',
                'harga' => 1900000,
                'stok' => 8,
            ],
            [
                'nama' => 'Sepatu Forum',
                'kategori_id' => 1,
                'merek_id' => 2,
                'deskripsi' => 'Sepatu Forum merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'FORUM-1.png',
                'gambarproduk1' => 'FORUM-1.avif',
                'gambarproduk2' => 'FORUM-2.avif',
                'gambarproduk3' => 'FORUM-3.avif',
                'harga' => 1400000,
                'stok' => 5,
            ],
            [
                'nama' => 'Headband Elite',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Headband Elite merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'HEADBAND-ELITE-1.png',
                'gambarproduk1' => 'HEADBAND-ELITE-1.avif',
                'gambarproduk2' => 'HEADBAND-ELITE-2.avif',
                'gambarproduk3' => 'HEADBAND-ELITE-2.avif',
                'harga' => 500000,
                'stok' => 10,
            ],
            [
                'nama' => 'Jaket Anthony',
                'kategori_id' => 5,
                'merek_id' => 2,
                'deskripsi' => 'Jaket Anthony merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'JAKET-ANTHONY-1.png',
                'gambarproduk1' => 'JAKET-ANTHONY-1.avif',
                'gambarproduk2' => 'JAKET-ANTHONY-2.avif',
                'gambarproduk3' => 'JAKET-ANTHONY-3.avif',
                'harga' => 1400000,
                'stok' => 10,
            ],
            [
                'nama' => 'Jersey Adidas',
                'kategori_id' => 2,
                'merek_id' => 2,
                'deskripsi' => 'Jersey Adidas merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'JERSEY-ADIDAS-1.png',
                'gambarproduk1' => 'JERSEY-ADIDAS-1.avif',
                'gambarproduk2' => 'JERSEY-ADIDAS-2.avif',
                'gambarproduk3' => 'JERSEY-ADIDAS-3.avif',
                'harga' => 1500000,
                'stok' => 5,
            ],
            [
                'nama' => 'Jersey Atlanta',
                'kategori_id' => 2,
                'merek_id' => 1,
                'deskripsi' => 'Jersey Atlanta merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'JERSEY-ATLANTA-1.png',
                'gambarproduk1' => 'JERSEY-ATLANTA-1.avif',
                'gambarproduk2' => 'JERSEY-ATLANTA-2.avif',
                'gambarproduk3' => 'JERSEY-ATLANTA-2.avif',
                'harga' => 1800000,
                'stok' => 8,
            ],
            [
                'nama' => 'Jersey Chicago',
                'kategori_id' => 2,
                'merek_id' => 1,
                'deskripsi' => 'Jersey Chicago merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'JERSEY-CHICAGO-1.png',
                'gambarproduk1' => 'JERSEY-CHICAGO-1.avif',
                'gambarproduk2' => 'JERSEY-CHICAGO-2.avif',
                'gambarproduk3' => 'JERSEY-CHICAGO-2.avif',
                'harga' => 1800000,
                'stok' => 8,
            ],
            [
                'nama' => 'Jersey Dallas',
                'kategori_id' => 2,
                'merek_id' => 1,
                'deskripsi' => 'Jersey Dallas merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'JERSEY-DALLAS-1.png',
                'gambarproduk1' => 'JERSEY-DALLAS-1.avif',
                'gambarproduk2' => 'JERSEY-DALLAS-2.avif',
                'gambarproduk3' => 'JERSEY-DALLAS-2.avif',
                'harga' => 1900000,
                'stok' => 9,
            ],
            [
                'nama' => 'Jersey Memphis',
                'kategori_id' => 2,
                'merek_id' => 1,
                'deskripsi' => 'Jersey Memphis merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'JERSEY-MEMPHIS-1.png',
                'gambarproduk1' => 'JERSEY-MEMPHIS-1.avif',
                'gambarproduk2' => 'JERSEY-MEMPHIS-2.avif',
                'gambarproduk3' => 'JERSEY-MEMPHIS-2.avif',
                'harga' => 1700000,
                'stok' => 10,
            ],
            [
                'nama' => 'Jersey Toronto',
                'kategori_id' => 2,
                'merek_id' => 1,
                'deskripsi' => 'Jersey Toronto merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'JERSEY-TORONTO-1.png',
                'gambarproduk1' => 'JERSEY-TORONTO-1.avif',
                'gambarproduk2' => 'JERSEY-TORONTO-2.avif',
                'gambarproduk3' => 'JERSEY-TORONTO-2.avif',
                'harga' => 1500000,
                'stok' => 10,
            ],
            [
                'nama' => 'Kaos Kaki Plus',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Kaos Kaki Plus merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'KK-PLUS-1.png',
                'gambarproduk1' => 'KK-PLUS-1.avif',
                'gambarproduk2' => 'KK-PLUS-2.avif',
                'gambarproduk3' => 'KK-PLUS-3.avif',
                'harga' => 100000,
                'stok' => 70,
            ],
            [
                'nama' => 'Kaos Kaki Running',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Kaos Kaki Running merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'KK-RUNNING-1.png',
                'gambarproduk1' => 'KK-RUNNING-1.avif',
                'gambarproduk2' => 'KK-RUNNING-2.avif',
                'gambarproduk3' => 'KK-RUNNING-3.avif',
                'harga' => 100000,
                'stok' => 60,
            ],
            [
                'nama' => 'Kaos Kaki Trail',
                'kategori_id' => 3,
                'merek_id' => 1,
                'deskripsi' => 'Kaos Kaki Trail merupakan bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo architecto adipisci, doloribus molestias recusandae dolores corporis consequatur tenetur quidem dolore accusantium nesciunt,',
                'gambarproduk' => 'KK-TRAIL-1.png',
                'gambarproduk1' => 'KK-TRAIL-1.avif',
                'gambarproduk2' => 'KK-TRAIL-2.avif',
                'gambarproduk3' => 'KK-TRAIL-3.avif',
                'harga' => 100000,
                'stok' => 60,
            ],
        ]);
    }
}
